import type { PortalSnapshot } from "./portalApi";

export const mockSnapshot: PortalSnapshot = {
  user: {
    id: 1,
    name: "Customer",
    email: "customer@example.com",
  },
  workspace: {
    id: 1,
    name: "Leaderbot workspace",
    slug: "workspace-1",
  },
  aiIdentity: {
    workspaceId: 1,
    name: "Leaderbot",
    instructions: "Help customers with clear, useful answers.",
    tone: "Helpful",
    language: "nl",
    modelDefault: "default",
  },
  channels: [
    {
      id: 1,
      workspaceId: 1,
      channel: "facebook_messenger",
      status: "disconnected",
      externalId: null,
      displayName: null,
      lastCheckedAt: null,
    },
  ],
  usage: {
    workspaceId: 1,
    period: "today",
    plan: {
      name: "Free",
      billingStatus: "free",
    },
    messageCount: 18,
    imageCount: 6,
    blockedCount: 0,
    limits: {
      imagesPerDay: 20,
      messagesPerWindow: 30,
      messageWindowSeconds: 60,
    },
    remaining: {
      imagesToday: 14,
    },
    upgrade: {
      recommended: false,
      reason: null,
    },
    upgradeRequests: [],
  },
  knowledgeStore: {
    workspaceId: 1,
    totalSources: 2,
    activeSources: 1,
    lastUpdate: "2026-01-15T09:00:00.000Z",
    sources: [
      {
        id: 1,
        workspaceId: 1,
        sourceType: "website",
        name: "Customer FAQ",
        sourceReference: "https://example.com/faq",
        status: "active",
        itemCount: 12,
        lastIndexedAt: "2026-01-15T09:00:00.000Z",
        metadata: {},
        createdAt: "2026-01-10T09:00:00.000Z",
        updatedAt: "2026-01-15T09:00:00.000Z",
      },
      {
        id: 2,
        workspaceId: 1,
        sourceType: "manual_text",
        name: "Brand voice notes",
        sourceReference: null,
        status: "queued",
        itemCount: 0,
        lastIndexedAt: null,
        metadata: {},
        createdAt: "2026-01-16T09:00:00.000Z",
        updatedAt: "2026-01-16T09:00:00.000Z",
      },
    ],
  },
  privacy: {
    privacy: "/privacy",
    terms: "/terms",
    dataDeletion: "/data-deletion",
    exportRequest: "mailto:privacy@leaderbot.live?subject=Leaderbot data export",
    deletionRequest: "mailto:privacy@leaderbot.live?subject=Leaderbot data deletion",
    controls: {
      allowKnowledgeIndexing: true,
      allowUsageAnalytics: false,
      imageMemoryRetentionDays: 30,
      createdAt: new Date(0).toISOString(),
      updatedAt: new Date(0).toISOString(),
    },
  },
};
